# Generated by Django 2.2.13 on 2020-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200730_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
